services:
  postgres:
    image: postgres:16
    container_name: football_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: football_user
      POSTGRES_PASSWORD: football_password
      POSTGRES_DB: football_db

    ports:
      - "5432:5432"

    volumes:
      - football_postgres_data:/var/lib/postgresql/data

volumes:
  football_postgres_data:
